export * from './fuel.types';
export * from './text/type.types';
export * from './ambulance.type';
export * from './emergency.type';
export * from './permission'
export * from './person.type'
export * from './department.type'
export * from './staff.type'
export * from './payload/appointment.type'
