name: Auto Merge PRs

on:
  pull_request_target:
    types:
      - labeled
      - synchronize

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check for merge-ready label
        id: check_label
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const labels = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });
            const hasLabel = labels.data.some(label => label.name === 'merge-ready');
            console.log(`PR has merge-ready label: ${hasLabel}`);
            return hasLabel.toString();

      - name: Checkout code
        if: steps.check_label.outputs.result == 'true'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
          
      - name: Auto-merge PR
        if: steps.check_label.outputs.result == 'true'
        run: |
          echo "Attempting to merge PR #${{ github.event.pull_request.number }}"
          # Get PR title to use as commit message
          PR_TITLE=$(gh pr view ${{ github.event.pull_request.number }} --json title -q .title)
          # Use PR title as commit message
          gh pr merge ${{ github.event.pull_request.number }} --merge --subject="$PR_TITLE"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
