name: Publish In github page

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pnmpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install NodeJS dependencies
        run: pnpm install
      - name: Build
        run: pnpm run-script build
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: deploy_dist
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: deploy_dist
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh_pages
          FOLDER: deploy_dist/tevet-troc-client/browser
